### ISSUE TITLE
Pressing BACK after Logout 

### ISSUE THREAD

**Issue by ericpostolache** [irinacovrescu/mps#5]
When pressing BACK button after logging out as an ADMIN, I am redirected to AdminMenuActivity.

You should not be able to go back to AdminMenuActivity after pressing logout without logging in again!

![Screenshot from 2019-10-30 11-11-04](https://user-images.githubusercontent.com/48095008/67844372-49eaa200-fb06-11e9-8d56-526df38a3341.png)

![Screenshot from 2019-10-30 11-11-10](https://user-images.githubusercontent.com/48095008/67844396-55d66400-fb06-11e9-8442-6c272fdcbc12.png)

**Comment by irinacovrescu** [comment]
Not done yet
